#Pandas Demo
Usado o tutorial [Python Pandas Tutorial (Part 1): Getting Started with Data Analysis - Installation and Loading Data](https://www.youtube.com/watch?v=ZyhVh-qRZPA).

In [2]:
# Importar bibliotecas
import pandas as pd

In [4]:
# ler arquivo
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/gold_price.csv')

In [5]:
df.shape
# (linha, coluna)

(1718, 81)

In [7]:
# selecionar todas as colunas
pd.set_option('display.max_columns',81)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1718 entries, 0 to 1717
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date           1718 non-null   object
 1   Open           1718 non-null   float64
 2   High           1718 non-null   float64
 3   Low            1718 non-null   float64
 4   Close          1718 non-null   float64
 5   Adj Close      1718 non-null   float64
 6   Volume         1718 non-null   int64
 7   SP_open        1718 non-null   float64
 8   SP_high        1718 non-null   float64
 9   SP_low         1718 non-null   float64
 10  SP_close       1718 non-null   float64
 11  SP_Ajclose     1718 non-null   float64
 12  SP_volume      1718 non-null   int64
 13  DJ_open        1718 non-null   float64
 14  DJ_high        1718 non-null   float64
 15  DJ_low         1718 non-null   float64
 16  DJ_close       1718 non-null   float64
 17  DJ_Ajclose     1718 non-null   float64
 18  DJ_volume      1718 non-null   int64
 19  EG_open        1718 non-null   float64
 20  EG_high        1718 non-null   float64
 21  EG_low         1718 non-null   float64
 22  EG_close       1718 non-null   float64
 23  EG_Ajclose     1718 non-null   float64
 24  EG_volume      1718 non-null   int64
 25  EU_Price       1718 non-null   float64
 26  EU_open        1718 non-null   float64
 27  EU_high        1718 non-null   float64
 28  EU_low         1718 non-null   float64
 29  EU_Trend       1718 non-null   int64
 30  OF_Price       1718 non-null   float64
 31  OF_Open        1718 non-null   float64
 32  OF_High        1718 non-null   float64
 33  OF_Low         1718 non-null   float64
 34  OF_Volume      1718 non-null   int64
 35  OF_Trend       1718 non-null   int64
 36  OS_Price       1718 non-null   float64
 37  OS_Open        1718 non-null   float64
 38  OS_High        1718 non-null   float64
 39  OS_Low         1718 non-null   float64
 40  OS_Trend       1718 non-null   int64
 41  SF_Price       1718 non-null   int64
 42  SF_Open        1718 non-null   int64
 43  SF_High        1718 non-null   int64
 44  SF_Low         1718 non-null   int64
 45  SF_Volume      1718 non-null   int64
 46  SF_Trend       1718 non-null   int64
 47  USB_Price      1718 non-null   float64
 48  USB_Open       1718 non-null   float64
 49  USB_High       1718 non-null   float64
 50  USB_Low        1718 non-null   float64
 51  USB_Trend      1718 non-null   int64
 52  PLT_Price      1718 non-null   float64
 53  PLT_Open       1718 non-null   float64
 54  PLT_High       1718 non-null   float64
 55  PLT_Low        1718 non-null   float64
 56  PLT_Trend      1718 non-null   int64
 57  PLD_Price      1718 non-null   float64
 58  PLD_Open       1718 non-null   float64
 59  PLD_High       1718 non-null   float64
 60  PLD_Low        1718 non-null   float64
 61  PLD_Trend      1718 non-null   int64
 62  RHO_PRICE      1718 non-null   int64
 63  USDI_Price     1718 non-null   float64
 64  USDI_Open      1718 non-null   float64
 65  USDI_High      1718 non-null   float64
 66  USDI_Low       1718 non-null   float64
 67  USDI_Volume    1718 non-null   int64
 68  USDI_Trend     1718 non-null   int64
 69  GDX_Open       1718 non-null   float64
 70  GDX_High       1718 non-null   float64
 71  GDX_Low        1718 non-null   float64
 72  GDX_Close      1718 non-null   float64
 73  GDX_Adj Close  1718 non-null   float64
 74  GDX_Volume     1718 non-null   int64
 75  USO_Open       1718 non-null   float64
 76  USO_High       1718 non-null   float64
 77  USO_Low        1718 non-null   float64
 78  USO_Close      1718 non-null   float64
 79  USO_Adj Close  1718 non-null   float64
 80  USO_Volume     1718 non-null   int64
dtypes: float64(58), int64(22), object(1)
memory usage: 1.1+ MB

In [9]:
# por padrão é impresso 20 colunas
# df.head(10)
df.tail(10)
# df
# print(df.to_string())

,Date,Open,High,Low,Close,Adj Close,Volume,SP_open,SP_high,SP_low,SP_close,SP_Ajclose,SP_volume,DJ_open,DJ_high,DJ_low,DJ_close,DJ_Ajclose,DJ_volume,EG_open,EG_high,EG_low,EG_close,EG_Ajclose,EG_volume,EU_Price,EU_open,EU_high,EU_low,EU_Trend,OF_Price,OF_Open,OF_High,OF_Low,OF_Volume,OF_Trend,OS_Price,OS_Open,OS_High,OS_Low,OS_Trend,SF_Price,SF_Open,SF_High,SF_Low,SF_Volume,SF_Trend,USB_Price,USB_Open,USB_High,USB_Low,USB_Trend,PLT_Price,PLT_Open,PLT_High,PLT_Low,PLT_Trend,PLD_Price,PLD_Open,PLD_High,PLD_Low,PLD_Trend,RHO_PRICE,USDI_Price,USDI_Open,USDI_High,USDI_Low,USDI_Volume,USDI_Trend,GDX_Open,GDX_High,GDX_Low,GDX_Close,GDX_Adj Close,GDX_Volume,USO_Open,USO_High,USO_Low,USO_Close,USO_Adj Close,USO_Volume
1708,2018-12-17,117.370003,118.029999,117.349998,117.870003,117.870003,8454900,259.399994,260.649994,253.529999,255.360001,253.877457,165492300,23986.83008,24088.08008,23456.88086,23592.98047,23592.98047,466740000,2.90,3.20,2.90,3.20,3.20,1537700,1.1347,1.1308,1.1360,1.1299,1,59.61,60.25,61.21,58.64,246030,0,49.32,51.30,51.84,49.03,0,38169,37965,38208,37905,8620,1,2.857,2.895,2.898,2.848,0,793.10,787.40,798.25,782.70,1,1188.00,1170.00,1194.2,1167.9,1,2530,97.175,97.425,97.470,97.130,360,0,20.290001,20.650000,20.280001,20.610001,20.501528,67083000,10.89,10.91,10.41,10.45,10.45,40129600
1709,2018-12-18,117.849998,118.199997,117.809998,118.150002,118.150002,7542900,257.200012,257.950012,253.279999,255.080002,253.599075,134515100,23769.13086,23927.76953,23516.01953,23675.64063,23675.64063,408070000,3.15,3.35,3.05,3.25,3.25,1660600,1.1361,1.1346,1.1402,1.1336,1,56.26,59.00,59.24,55.89,398560,0,46.30,49.31,49.56,45.80,0,37453,38002,38042,37415,13610,0,2.823,2.859,2.861,2.818,0,792.90,793.25,795.75,786.10,0,1176.00,1187.05,1189.2,1173.5,0,2515,96.570,96.605,96.645,96.155,13570,0,20.540001,21.170000,20.530001,21.090000,20.979000,79518700,10.41,10.41,9.73,9.79,9.79,56381900
1710,2018-12-19,118.239998,118.959999,117.400002,117.430000,117.430000,13827500,255.169998,259.399994,249.350006,251.259995,249.801239,214992800,23693.33008,24057.33984,23162.64063,23323.66016,23323.66016,503550000,3.25,3.45,3.05,3.05,3.05,1642600,1.1377,1.1361,1.1442,1.1360,1,57.24,56.51,58.11,56.04,319370,1,47.08,46.31,48.01,46.01,1,37679,37455,37830,37368,11050,1,2.762,2.819,2.861,2.750,0,787.70,792.75,799.30,785.60,0,1195.00,1176.70,1208.7,1173.8,1,2500,96.484,96.390,96.565,95.995,20140,0,21.090000,21.469999,19.900000,19.950001,19.845001,120753200,9.97,10.20,9.92,10.02,10.02,38468500
1711,2018-12-20,119.110001,119.739998,118.680000,119.239998,119.239998,18615100,249.860001,251.619995,244.649994,247.169998,245.735001,252053400,23224.11914,23282.19922,22644.31055,22859.59961,22859.59961,576700000,3.15,3.25,2.90,3.05,3.05,1636900,1.1446,1.1377,1.1487,1.1371,1,54.35,56.49,56.75,54.28,299450,0,46.06,47.07,47.20,45.39,0,37525,37391,37655,37185,15980,0,2.808,2.767,2.814,2.748,1,796.40,787.60,798.80,785.00,1,1188.45,1195.00,1204.1,1177.6,0,2500,95.728,96.455,96.515,95.630,31350,0,20.530001,20.840000,20.340000,20.670000,20.670000,94498200,9.81,9.96,9.64,9.72,9.72,44132600
1712,2018-12-21,119.190002,119.250000,118.570000,118.720001,118.720001,13629800,246.740005,249.710007,239.979996,240.699997,240.699997,255345600,22871.74023,23254.58984,22396.33984,22445.36914,22445.36914,900510000,3.05,3.15,2.90,3.00,3.00,2328500,1.1369,1.1447,1.1477,1.1353,0,53.82,54.97,55.33,52.79,226340,0,45.08,46.08,46.47,44.86,0,37256,37413,37605,37201,13110,0,2.788,2.801,2.810,2.781,0,789.05,796.50,798.60,788.00,0,1158.90,1188.80,1190.4,1155.5,0,2480,96.455,95.875,96.560,95.730,20130,1,20.680000,20.770000,20.270000,20.440001,20.440001,63178700,9.62,9.78,9.54,9.57,9.57,38901200
1713,2018-12-24,119.570000,120.139999,119.570000,120.019997,120.019997,9736400,239.039993,240.839996,234.270004,234.339996,234.339996,147311600,22317.27930,22339.86914,21792.19922,21792.19922,21792.19922,308420000,2.95,3.05,2.90,2.95,2.95,655100,1.1400,1.1370,1.1439,1.1350,1,50.47,53.49,54.66,50.36,76220,0,42.27,45.34,45.95,42.22,0,37541,37325,37600,37305,9460,1,2.736,2.826,2.826,2.733,0,788.40,791.85,798.30,788.30,0,1172.80,1163.40,1177.6,1157.9,1,2480,96.007,96.440,96.440,95.870,13930,0,20.700001,21.110001,20.650000,21.090000,21.090000,60507000,9.49,9.52,9.28,9.29,9.29,21598200
1714,2018-12-26,120.620003,121.000000,119.570000,119.660004,119.660004,14293500,235.970001,246.179993,233.759995,246.179993,246.179993,218485400,21857.73047,22878.91992,21712.52930,22878.44922,22878.44922,433080000,3.00,3.05,2.90,3.00,3.00,746300,1.1353,1.1363,1.1423,1.1342,0,54.47,50.84,55.29,49.93,77000,1,46.39,43.09,46.78,42.34,1,38253,37607,38489,37574,19410,1,2.810,2.751,2.815,2.720,1,799.25,788.75,804.30,788.75,1,1190.10,1176.00,1191.0,1175.5,1,2480,96.568,96.100,96.650,96.020,15660,1,21.350000,21.400000,20.530001,20.620001,20.620001,76365200,9.25,9.92,9.23,9.90,9.90,40978800
1715,2018-12-27,120.570000,120.900002,120.139999,120.570000,120.570000,11874400,242.570007,248.289993,238.960007,248.070007,248.070007,186267300,22629.06055,23138.89063,22267.41992,23138.82031,23138.82031,407940000,2.95,3.00,2.90,2.95,2.95,744000,1.1430,1.1353,1.1457,1.1349,1,52.16,54.65,54.67,51.94,102590,0,45.23,46.41,46.41,44.20,0,38690,38274,38783,38081,19650,1,2.774,2.803,2.806,2.733,0,795.50,799.40,802.20,785.10,0,1196.00,1190.05,1198.4,1181.5,1,2470,96.001,96.460,96.495,95.935,20520,0,20.840000,21.000000,20.700001,20.969999,20.969999,52393000,9.59,9.65,9.37,9.62,9.62,36578700
1716,2018-12-28,120.800003,121.080002,120.720001,121.059998,121.059998,6864700,249.580002,251.399994,246.449997,247.750000,247.750000,153100200,23213.60938,23381.88086,22981.33008,23062.40039,23062.40039,336510000,2.85,2.95,2.85,2.90,2.90,1061100,1.1438,1.1429,1.1478,1.1424,1,52.20,53.44,53.80,51.60,17110,1,44.92,45.23,46.02,44.27,0,38706,38749,38880,38587,14200,1,2.716,2.768,2.781,2.713,0,790.25,795.60,800.50,787.75,0,1185.20,1196.00,1204.8,1179.5,0,2460,95.965,96.020,96.050,95.740,14170,0,20.889999,21.020000,20.570000,20.600000,20.600000,49835000,9.54,9.65,9.38,9.53,9.53,22803400
1717,2018-12-31,120.980003,121.260002,120.830002,121.250000,121.250000,8449400,249.559998,250.190002,247.470001,249.919998,249.919998,144299400,23153.93945,23333.17969,23118.30078,23327.46094,23327.46094,288830000,2.77,2.95,2.73,2.88,2.88,1031800,1.1470,1.1443,1.1470,1.1421,1,53.80,53.00,54.82,52.66,109110,1,45.00,45.34,46.36,44.59,0,38821,38798,38877,38550,13780,1,2.686,2.730,2.745,2.679,0,801.40,795.95,802.80,793.10,1,1197.50,1185.20,1198.8,1183.6,1,0,95.735,95.965,96.070,95.585,16650,0,20.700001,21.129999,20.559999,21.090000,21.090000,53866600,9.63,9.71,9.44,9.66,9.66,28417400